import type { Workflow } from "./types";

export const WORKFLOWS: Workflow[] = [
  {
    id: "w-tech-stack",
    slug: "tech-stack",
    title: "Tech-Stack-Foundation",
    category: "system",
    stage: "operations",
    status: "done",
    summary:
      "Vollständiger Tech-Stack des Hagi-Shops. Entschieden durch 7-Achsen-Methodik (Snyk, Maintenance, Bus-Faktor, DSGVO, Lock-In, Kosten, Ecosystem). Dokumentiert in ADR-001.",
    trigger: "Foundation-Entscheidung (permanent gültig bis Revision)",
    steps: [
      "Hosting: Hetzner CX32 + Coolify (~15€/Monat, EU-DE, Docker-Standard)",
      "CDN: Cloudflare Free (WAF + Bandwidth Alliance mit Backblaze = 0€ Egress)",
      "DB: Postgres 15 self-hosted (volle Kontrolle, 0€, Standard-SQL kein Lock-In)",
      "ORM: Prisma 5 (Snyk 96, TypeScript-Types, Migration-Tool)",
      "Auth: Auth.js v5 (Snyk 87, Vercel-backed, DB-Sessions in unserer Postgres)",
      "Payment: Stripe (BGB § 312j konform, Klarna/SEPA/Apple Pay/Google Pay)",
      "Email: Resend (EU-Region Irland, React-Email-native)",
      "PDF: @react-pdf/renderer (pure React, klein, kein Chrome-Overhead)",
      "Storage: Backblaze B2 + Cloudflare CDN (S3-API, EU Amsterdam)",
      "Search: Postgres Full-Text-Search (GIN-Index + pg_trgm, reicht für 10k+ Produkte)",
      "Analytics: Plausible Cloud 9€/Monat (DSGVO-konform, kein Cookie-Banner)",
      "Error-Monitoring: Sentry EU (Frankfurt, Free bis 5k Events)",
      "Rate-Limiting: Cloudflare WAF + Upstash Redis (gestuft)",
      "Background-Jobs: Coolify Cron + Postgres-Queue",
      "Validation: Zod 3 (TypeScript-Standard)",
      "Testing: Vitest + Playwright",
    ],
    risks: [
      {
        id: "r-coolify-bus-factor",
        title: "Coolify Bus-Faktor mittelmäßig",
        description: "Coolify hat einen Haupt-Maintainer (Andras Bacsai). Wenn er aufhört, langfristige Maintenance unsicher.",
        level: "medium",
        consequence: "Coolify-UI evtl. nicht mehr supported in 2-3 Jahren.",
        mitigation: "Fallback: plain Docker-Compose-Setup vorbereiten. Coolify ist UI, nicht Runtime — App läuft auch ohne weiter.",
        mitigationStatus: "planned",
      },
      {
        id: "r-vendor-shutdown",
        title: "Externe Vendor-Shutdowns",
        description: "Resend, Backblaze, Plausible — alles SaaS. Bei Shutdown brauchen wir Migration-Plan.",
        level: "low",
        consequence: "Service-Unterbrechung 1-3 Tage bei Notfall-Migration.",
        mitigation: "ADR-001 'Migrationspfade weg' definiert Plan B für jede Schicht. Alle nutzen Standard-APIs (S3, SMTP, REST).",
        mitigationStatus: "done",
        codeRef: "docs/adr/adr-001-tech-stack.md",
      },
      {
        id: "r-cost-explosion",
        title: "Kosten-Cliff bei Volumen-Skalierung",
        description: "Bei 1000+ Orders/Monat: Sentry 26€, Resend 20$, Upstash 10$ etc. = ~95€/Monat fix.",
        level: "low",
        consequence: "Kosten verdreifachen sich. Trotzdem 95% günstiger als Shopify.",
        mitigation: "Volumen-getriebene Re-Evaluation. ADR-001 dokumentiert 'Wann revisten'.",
        mitigationStatus: "done",
        codeRef: "docs/adr/adr-001-tech-stack.md",
      },
      {
        id: "r-self-host-ops",
        title: "Selbst-Betrieb = unsere Verantwortung",
        description: "Backups, Updates, Monitoring, Security-Patches müssen wir selbst betreiben.",
        level: "high",
        consequence: "Bei Schlamperei: Datenverlust, Downtime, DSGVO-Verstoß.",
        mitigation: "Pflicht: täglicher pg_dump, GitHub Actions CI, Coolify Health-Checks, Sentry Release-Tracking. Plus Runbook für Incidents.",
        mitigationStatus: "planned",
      },
    ],
    security: [
      { id: "s-eu-only", title: "Alle Services EU-Region", description: "Kein US-Provider für PII-Daten.", status: "done", codeRef: "docs/adr/adr-001-tech-stack.md" },
      { id: "s-low-lockin", title: "Niedriger Lock-In pro Schicht", description: "Jede Schicht hat dokumentierten Migrationspfad Plan B.", status: "done", codeRef: "docs/adr/adr-001-tech-stack.md" },
      { id: "s-snyk-monitoring", title: "Snyk-Scores aller Pakete > 80", description: "Audit pro Quartal. Bei < 80: Alternative evaluieren.", status: "planned" },
      { id: "s-cve-watch", title: "GitHub Security Advisories aktiv", description: "Dependabot-Alerts für alle kritischen Pakete.", status: "planned" },
    ],
    frontend: [
      { page: "ADR-001 Tech-Stack", change: "Komplette Begründung pro Schicht inkl. Snyk-Scores und Migrationspfaden", status: "done" },
      { page: "Stack-Evaluation-Template", change: "Wiederverwendbar für Future-Entscheidungen (vault)", status: "done" },
    ],
    codeRefs: [
      "docs/adr/adr-001-tech-stack.md",
      "~/vault/agency/intern/stack-evaluation-template.md",
    ],
    openQuestions: [
      "Cloudinary statt Backblaze wenn Bilder-Volumen > 5 GB?",
      "Meilisearch self-host wenn Hagi > 1000 Produkte hat?",
    ],
  },
  {
    id: "w-db-security",
    slug: "db-security-haertung",
    title: "Datenbank-Härtung (7 Schichten)",
    category: "compliance",
    stage: "operations",
    status: "in-progress",
    summary:
      "Single-Postgres-DB ist OK — aber nur mit Defense-in-Depth. 7 Härtungsschichten gegen DB-Breach. Industry-Standard bei Premium-Shops, nicht separate Auth-DB.",
    trigger: "Bei Production-Deployment + bei jeder Postgres-Konfig-Änderung",
    steps: [
      "Schicht 1: Network-Isolation — Postgres lauscht nur auf 127.0.0.1, Cloudflare WAF davor",
      "Schicht 2: Application-Isolation — Next.js als non-root, Least-Privilege DB-User (app/migrate/readonly getrennt)",
      "Schicht 3: Encryption-at-Rest — Hetzner LUKS Disk-Encryption + pgcrypto für sensitive Felder",
      "Schicht 4: Encryption-in-Transit — Postgres TLS Pflicht (keine Cleartext-Verbindungen)",
      "Schicht 5: Backup-Encryption — pg_dump GPG-verschlüsselt + separater Backblaze-Bucket",
      "Schicht 6: Audit-Trail — AuditLog für alle Admin-Aktionen + Postgres log_connections",
      "Schicht 7: Secrets-Management — Coolify ENV-Vars + 90-Tage Password-Rotation",
    ],
    risks: [
      {
        id: "r-db-breach-direct",
        title: "Externer Zugriff auf Postgres-Port 5432",
        description: "Wenn Postgres öffentlich erreichbar, kann jeder Brute-Force versuchen.",
        level: "high",
        consequence: "Komplett-Kompromittierung möglich.",
        mitigation: "Schicht 1: Postgres bind 127.0.0.1, Firewall blockt Port 5432 extern.",
        mitigationStatus: "planned",
      },
      {
        id: "r-app-user-privesc",
        title: "App-User hat zu viele Rechte",
        description: "Wenn Prisma als 'postgres'-superuser läuft: SQL-Injection-Bug = DROP TABLE möglich.",
        level: "high",
        consequence: "Datenverlust + Buchhaltungs-Gap (10-Jahre AO §147).",
        mitigation: "Schicht 2: Eigener User 'hagi_app' mit nur SELECT/INSERT/UPDATE/DELETE. Migrationen via separatem 'hagi_migrate'-User.",
        mitigationStatus: "planned",
      },
      {
        id: "r-backup-leak",
        title: "Backup-Datei unverschlüsselt geleaked",
        description: "pg_dump.sql liegt auf Backup-Storage. Wenn Storage kompromittiert: alle PII liegen offen.",
        level: "high",
        consequence: "Massiver DSGVO-Verstoß. Bußgeld bis 4% Jahresumsatz.",
        mitigation: "Schicht 5: GPG-Verschlüsselung mit Master-Key offline. Backup-Bucket separater Backblaze-Account.",
        mitigationStatus: "planned",
      },
      {
        id: "r-cleartext-conn",
        title: "Postgres-Verbindung ohne TLS",
        description: "Wenn DB lokal aber TLS nicht erzwungen: Man-in-the-Middle möglich bei Container-Network.",
        level: "medium",
        consequence: "Passwörter + Daten im Klartext auf Wire.",
        mitigation: "Schicht 4: Postgres ssl=on, hostssl in pg_hba.conf, DATABASE_URL mit sslmode=require.",
        mitigationStatus: "planned",
      },
      {
        id: "r-secrets-in-code",
        title: "DB-Password versehentlich im Code committed",
        description: "Junior-Fehler: Password in .env.example oder Dockerfile.",
        level: "medium",
        consequence: "GitHub-Public: Bots scannen sofort, Postgres binnen Minuten kompromittiert.",
        mitigation: "Schicht 7: Pre-commit-Hook mit gitleaks. .env strikt gitignored. Coolify ENV-Vars.",
        mitigationStatus: "planned",
      },
      {
        id: "r-no-audit-trail",
        title: "Kein Audit bei DB-Änderungen",
        description: "Wenn Hagi versehentlich (oder bewusst) Order ändert: kein Beweis was war.",
        level: "medium",
        consequence: "Streitfälle nicht beweisbar. DSGVO-Auskunfts-Pflicht verletzt.",
        mitigation: "Schicht 6: AuditLog für alle Admin-Aktionen (schon implementiert). Plus log_statement=mod auf DB-Level.",
        mitigationStatus: "in-progress",
        codeRef: "lib/services/audit.ts",
      },
    ],
    security: [
      {
        id: "s-pg-bind",
        title: "Schicht 1: Postgres bind 127.0.0.1",
        description: "Lauscht nicht auf öffentlichen Interfaces. Coolify-internes Docker-Network.",
        status: "planned",
      },
      {
        id: "s-least-priv",
        title: "Schicht 2: Least-Privilege DB-User",
        description: "3 User: hagi_app (CRUD), hagi_migrate (DDL), hagi_readonly (Reports/Steuerberater).",
        status: "planned",
      },
      {
        id: "s-luks",
        title: "Schicht 3: LUKS Disk-Encryption",
        description: "Hetzner Volume mit Full-Disk-Encryption. Schutz bei physischem Disk-Diebstahl.",
        status: "planned",
      },
      {
        id: "s-pgcrypto",
        title: "Schicht 3b: pgcrypto für sensitive Felder",
        description: "passwordHash und passwordResetTokenHash sind bereits gehasht (argon2id geplant).",
        status: "in-progress",
        codeRef: "lib/security/tokens.ts",
      },
      {
        id: "s-tls",
        title: "Schicht 4: Postgres TLS Pflicht",
        description: "ssl=on + hostssl in pg_hba.conf + sslmode=require in App.",
        status: "planned",
      },
      {
        id: "s-backup-gpg",
        title: "Schicht 5: GPG-verschlüsselte Backups",
        description: "Daily pg_dump | gpg --encrypt → Backblaze separater Bucket. 30-Tage-Retention.",
        status: "planned",
      },
      {
        id: "s-audit-app",
        title: "Schicht 6: AuditLog im App-Code",
        description: "Alle Admin-Aktionen via logAudit() — bereits implementiert.",
        status: "done",
        codeRef: "lib/services/audit.ts",
      },
      {
        id: "s-audit-pg",
        title: "Schicht 6b: Postgres log_connections + log_statement=mod",
        description: "DB-Level Audit zusätzlich zu App-Level.",
        status: "planned",
      },
      {
        id: "s-coolify-env",
        title: "Schicht 7: Secrets in Coolify ENV-Vars",
        description: "Nicht im Code, nicht in .env-Files. Coolify encrypted at rest.",
        status: "planned",
      },
      {
        id: "s-pw-rotation",
        title: "Schicht 7b: 90-Tage Password-Rotation",
        description: "DB-Passwords + API-Keys + Webhook-Secrets alle 90 Tage rotieren.",
        status: "planned",
      },
      {
        id: "s-gitleaks",
        title: "Schicht 7c: Pre-commit gitleaks",
        description: "Verhindert versehentliches Committen von Secrets.",
        status: "planned",
      },
      {
        id: "s-argon2id",
        title: "Bonus: argon2id für Passwörter",
        description: "Statt bcrypt — moderner, gegen GPU-Cracking gehärtet.",
        status: "planned",
      },
      {
        id: "s-2fa-admin",
        title: "Bonus: 2FA Pflicht für Admin",
        description: "TOTP für Hagi-Admin-Login.",
        status: "planned",
      },
    ],
    frontend: [
      { page: "ADR-002 Database Security", change: "Schicht-für-Schicht Implementierungs-Guide", status: "planned" },
      { page: "Runbook: DB-Härtung", change: "Schritt-für-Schritt für Production-Deploy", status: "planned" },
    ],
    codeRefs: [
      "docs/adr/adr-001-tech-stack.md",
      "docs/adr/adr-002-database-security.md (geplant)",
      "lib/security/tokens.ts",
      "lib/services/audit.ts",
    ],
    openQuestions: [
      "Hardware-Security-Module für Master-Backup-Key (overkill für jetzt)?",
      "Read-Replica für Reports — Aufwand vs Wert?",
      "Postgres-Container vs Hetzner-Managed-Postgres (Add-On 25€/Monat)?",
    ],
  },
  {
    id: "w-browse",
    slug: "browse-discovery",
    title: "Browse & Discovery",
    category: "customer",
    stage: "stage-1",
    status: "done",
    summary: "Kunde landet auf Startseite, scrollt durch Editorial-Sections, navigiert zur Kollektion.",
    trigger: "Direkter Aufruf, Google-Search, Social-Link",
    steps: [
      "Hero mit 3D-Coverflow auto-rotiert",
      "Trust-Strip + Bestseller mit Progressive-Blur-Hover",
      "Why-Hagi-Accordion (5 USP-Panels) expandiert per Hover",
      "Klick auf Bestseller → Produkt-Detail",
      "Klick auf 'Zum Shop' → /produkte mit Filter",
    ],
    risks: [
      {
        id: "r-perf",
        title: "Performance bei großen Bildern",
        description: "Higgsfield-CDN-Bilder sind unkomprimiert, 1-3 MB pro Bild. Mobile Daten teuer.",
        level: "medium",
        consequence: "Lighthouse < 70, Mobile-Bounce-Rate steigt.",
        mitigation: "next/image AVIF + sizes-Attribut + lazy loading. Vor Live: alle Bilder auf 200 KB komprimieren.",
        mitigationStatus: "in-progress",
      },
      {
        id: "r-csp",
        title: "CSP blockt Bilder von neuer CDN",
        description: "Wenn Hagi später eigene Bilder hostet (S3/Cloudinary), CSP-Hosts müssen erweitert werden.",
        level: "low",
        consequence: "Bilder broken nach Migration.",
        mitigation: "CSP-Liste in next.config.mjs als ENV-Variable konfigurierbar machen.",
        mitigationStatus: "planned",
        codeRef: "next.config.mjs",
      },
    ],
    security: [
      { id: "s-csp", title: "CSP-Header strikt", description: "unsafe-eval nur in Dev, Strict in Prod.", status: "done", codeRef: "next.config.mjs" },
      { id: "s-noindex", title: "robots.txt erlaubt nur Storefront", description: "/admin, /playbook, /api ausgeschlossen.", status: "planned", codeRef: "app/robots.ts" },
    ],
    frontend: [
      { page: "Start", pageHref: "/", change: "Editorial-Hero + Carousel + Trust-Strip", status: "done" },
      { page: "Bestseller-Section", change: "Progressive-Blur-Hover", status: "done" },
      { page: "Why-Hagi", change: "5-Panel-Accordion", status: "done" },
    ],
    codeRefs: ["app/page.tsx", "components/home/HeroCarousel.tsx", "components/home/WhyHagiAccordion.tsx"],
  },
  {
    id: "w-product-detail",
    slug: "produkt-detail",
    title: "Produkt-Detail-View",
    category: "customer",
    stage: "stage-1",
    status: "done",
    summary: "Vollständige Datenblatt-Page mit Story, Knüpfer-Portrait, Pflege, Echtheits-Zertifikat.",
    trigger: "Klick auf Produktkarte",
    steps: [
      "Lazy-load Galerie mit Zoom",
      "Story + 30+ Datenblatt-Felder + Knüpfer-Portrait + Pflege + Zertifikat",
      "Klick 'In den Warenkorb' (kommt in Stage 2)",
      "WhatsApp-Berater Floating",
    ],
    risks: [
      {
        id: "r-compare-price",
        title: "comparePrice rechtswidrig (PAngV § 11)",
        description: "Streichpreise müssen 30 Tage vorher tatsächlich verlangt worden sein. Bei Direktimport nicht beweisbar.",
        level: "medium",
        consequence: "Abmahnung durch Verbraucherzentrale, ~500-1500 € Schadensersatz.",
        mitigation: "comparePrice umlabeln auf 'Vergleichswert im Fachhandel' ODER weg.",
        mitigationStatus: "planned",
        codeRef: "app/produkte/[slug]/page.tsx",
      },
      {
        id: "r-unikat-race",
        title: "Race-Condition bei Unikat-Cart-Add",
        description: "2 Kunden klicken gleichzeitig 'In Cart' für dasselbe Stück. Beide gehen zu Stripe.",
        level: "medium",
        consequence: "Doppelverkauf, manueller Storno, Vertrauensverlust.",
        mitigation: "Cart-Reservation 15min beim Add-to-Cart. SELECT FOR UPDATE beim Commit-Order.",
        mitigationStatus: "planned",
      },
    ],
    security: [
      { id: "s-product-snapshot", title: "OrderItem snapshottet alles", description: "Preis, Bild, Titel, Steuer eingefroren — auch wenn Produkt später gelöscht.", status: "done", codeRef: "prisma/schema.prisma" },
      { id: "s-schema-org", title: "Schema.org JSON-LD", description: "Product Markup für SEO + Snippets.", status: "done", codeRef: "app/produkte/[slug]/page.tsx" },
    ],
    frontend: [
      { page: "Produkt-Detail", pageHref: "/produkte/taebris-medaillon-240-170", change: "Editorial-Hybrid Story+Datenblatt", status: "done" },
    ],
    openQuestions: ["comparePrice: weg oder umlabeln?", "Cart-Reservation jetzt oder in Stage 6?"],
  },
  {
    id: "w-cart-add",
    slug: "cart-hinzufuegen",
    title: "Cart-Hinzufügen",
    category: "customer",
    stage: "stage-2",
    status: "in-progress",
    summary: "Add-to-Cart Logik mit Server-Side-Validation, LocalStorage-Persistence, Unikat-Limit.",
    trigger: "Klick 'In den Warenkorb' auf Produkt-Detail",
    steps: [
      "Client schickt { productId, quantity } via Server-Action",
      "validateCart() lädt Preise + Steuer aus DB",
      "Bei Unikat: max 1 forced",
      "Bei MAX_QUANTITY_PER_ITEM (5) Überschreitung: Error",
      "LocalStorage cart-store.ts speichert IDs+Quantities",
      "Cart-Badge im Header aktualisiert",
    ],
    risks: [
      {
        id: "r-tampering",
        title: "Client manipuliert Preis im Cart",
        description: "DevTools-User ändert Cart-LocalStorage zu price=1.",
        level: "high",
        consequence: "Bestellung über 1 Cent für 1.299 € Teppich. Stripe akzeptiert!",
        mitigation: "validateCart() ignoriert ALLE Client-Preise, lädt aus DB neu. Mass-Assignment-Schutz: nur productId+quantity extrahieren.",
        mitigationStatus: "done",
        codeRef: "lib/services/cart.ts",
      },
      {
        id: "r-cart-bloat",
        title: "User füllt Cart mit 10.000 Items",
        description: "Bot oder Trottel adds 999x jeden Teppich.",
        level: "low",
        consequence: "DB-Load + LocalStorage-Bloat.",
        mitigation: "MAX_ITEMS_IN_CART=20, MAX_QUANTITY_PER_ITEM=5",
        mitigationStatus: "done",
        codeRef: "lib/services/cart.ts",
      },
    ],
    security: [
      { id: "s-input-sanitize", title: "Input-Sanitization", description: "Nur productId (string) + quantity (int) akzeptiert.", status: "done" },
      { id: "s-server-truth", title: "Server-Side-Truth", description: "Preis/Steuer/Snapshots IMMER aus DB.", status: "done" },
      { id: "s-rate-limit", title: "Rate-Limit auf Cart-API", description: "30/min pro IP.", status: "planned" },
    ],
    frontend: [
      { page: "Cart-Page", pageHref: "/warenkorb", change: "Editorial-Redesign in Stage 2", status: "planned" },
      { page: "Cart-Badge im Header", change: "Live-Update bei Add", status: "done" },
    ],
  },
  {
    id: "w-checkout",
    slug: "checkout",
    title: "Checkout (Adresse + Versand + Discount)",
    category: "customer",
    stage: "stage-2",
    status: "planned",
    summary: "Single-Page-Checkout mit Adress-Form, Versandauswahl, Pickup-Option, Discount, AGB-Checkbox.",
    trigger: "Klick 'Zur Kasse' im Warenkorb",
    steps: [
      "Adresse eingeben (Billing + Shipping toggleable)",
      "Versandzone via Country-Code → ShippingRates anzeigen",
      "Pickup-im-Showroom als Option (cents=0)",
      "Discount-Code optional eingeben → previewDiscount()",
      "AGB + Widerruf + Datenschutz Checkboxen (jeweils Version snapshot)",
      "Bei Sonderanfertigung: extra Checkbox 'kein Widerruf'",
      "B2B: USt-ID + Firmen-Feld",
      "Klick 'Zahlungspflichtig bestellen' → Stripe Checkout Session",
    ],
    risks: [
      {
        id: "r-button-loesung",
        title: "BGB § 312j Button-Lösung verletzt",
        description: "Button-Text falsch ('Bestellen' statt 'Zahlungspflichtig bestellen').",
        level: "high",
        consequence: "Vertrag unwirksam. Kunde kann kostenlos zurücktreten.",
        mitigation: "Stripe Checkout Sessions sind out-of-the-box konform. Plus eigener Button-Text validiert.",
        mitigationStatus: "planned",
      },
      {
        id: "r-consent-missing",
        title: "AGB-Akzeptanz nicht beweisbar",
        description: "Kunde klagt: 'Habe nie zugestimmt'. Wir haben keinen Beweis.",
        level: "high",
        consequence: "Streitfall verloren, AGB unwirksam.",
        mitigation: "ConsentLog mit Versionierung + IP + Timestamp. AGB-Version auf Order snapshotted.",
        mitigationStatus: "done",
        codeRef: "lib/services/consent.ts",
      },
      {
        id: "r-vies",
        title: "VAT-ID nicht validiert bei B2B",
        description: "Kunde gibt FAKE-USt-ID an → Reverse-Charge fälschlicherweise angewendet → wir schulden Steuer.",
        level: "medium",
        consequence: "Nachforderung Finanzamt + Strafe.",
        mitigation: "VIES-API-Check vor Reverse-Charge.",
        mitigationStatus: "planned",
      },
      {
        id: "r-checkout-abandon",
        title: "Hohe Cart-Abandonment-Rate",
        description: "Premium-E-Commerce: 70% Abbruch vor Bezahlen.",
        level: "medium",
        consequence: "Umsatz-Verlust.",
        mitigation: "Apple Pay + Klarna + Express-Checkout. Abandoned-Cart-Mails. Trust-Strip prominent.",
        mitigationStatus: "planned",
      },
    ],
    security: [
      { id: "s-csrf", title: "Server Actions CSRF-protected", description: "Next.js Server Actions haben CSRF-Schutz built-in.", status: "done" },
      { id: "s-honeypot", title: "Honeypot gegen Bots", description: "Hidden Field das nur Bots ausfüllen.", status: "planned" },
      { id: "s-stripe-https", title: "Stripe HTTPS-only", description: "Card-Daten gehen NIE durch unseren Server.", status: "done" },
    ],
    frontend: [
      { page: "Checkout-Page", pageHref: "/checkout", change: "Editorial-Single-Page-Checkout", status: "planned" },
    ],
    openQuestions: ["Single-Page vs Multi-Step?", "Express Apple-Pay-Button oben?"],
  },
  {
    id: "w-stripe-payment",
    slug: "stripe-payment",
    title: "Stripe-Zahlung + Webhook",
    category: "system",
    stage: "stage-2",
    status: "planned",
    summary: "Stripe Checkout Session erzeugt, Kunde bezahlt, Webhook triggert Order-Anlage + Mail.",
    trigger: "Stripe sendet payment_intent.succeeded an /api/webhooks/stripe",
    steps: [
      "Webhook empfängt Event",
      "Signature-Verify via STRIPE_WEBHOOK_SECRET",
      "recordReceive() — Dedup-Check",
      "Wenn neu: Transaction { Order anlegen + redeemDiscount + Lagerbestand }",
      "markProcessed()",
      "Auto-Trigger: sendOrderConfirmation()",
      "Auto-Trigger: logAudit()",
    ],
    risks: [
      {
        id: "r-webhook-outage",
        title: "Webhook-Ausfall (Stripe oder unser System)",
        description: "Kunde bezahlt, Webhook kommt nicht an. Keine Order, kein Mail.",
        level: "high",
        consequence: "Kunde wartet auf Bestätigung. Customer-Support-Eskalation.",
        mitigation: "Stripe Retries 30x. Plus Page nach Stripe-Redirect zeigt Status. Plus daily Cron der Stripe-Sessions abgleicht.",
        mitigationStatus: "planned",
      },
      {
        id: "r-double-charge",
        title: "Doppelte Order durch Webhook-Retries",
        description: "Stripe retries → unser System verarbeitet 2x.",
        level: "high",
        consequence: "Doppel-Bestellung, Doppel-Mail.",
        mitigation: "providerEventId UNIQUE + recordReceive create-first-pattern.",
        mitigationStatus: "done",
        codeRef: "lib/services/webhook-dedup.ts",
      },
      {
        id: "r-signature-bypass",
        title: "Forged Webhook ohne Signature-Check",
        description: "Angreifer schickt fake payment_intent.succeeded → wir legen kostenlose Order an.",
        level: "high",
        consequence: "Massive Bestellungen ohne Bezahlung.",
        mitigation: "stripe.webhooks.constructEvent() mit secret. raw-body Parsing (Next.js bodyParser: false).",
        mitigationStatus: "planned",
      },
      {
        id: "r-idempotency",
        title: "Stripe-Calls ohne Idempotency-Key",
        description: "Retry erzeugt 2 Payment Intents.",
        level: "medium",
        consequence: "Buchhaltungs-Mismatch.",
        mitigation: "Idempotency-Key pro Order-Versuch (Hash aus Cart + Customer).",
        mitigationStatus: "planned",
      },
    ],
    security: [
      { id: "s-webhook-sig", title: "Webhook-Signature-Verify", description: "Stripe-Library prüft HMAC-SHA256.", status: "planned" },
      { id: "s-webhook-dedup", title: "Webhook-Dedup race-safe", description: "Create-First mit P2002-Catch.", status: "done", codeRef: "lib/services/webhook-dedup.ts" },
      { id: "s-payload-limit", title: "Payload max 100 KB", description: "DoS-Schutz.", status: "done", codeRef: "lib/services/webhook-dedup.ts" },
    ],
    frontend: [
      { page: "Stripe-Success-Redirect", pageHref: "/bestellung-bestaetigt", change: "Editorial-Confirmation-Page", status: "planned" },
    ],
  },
  {
    id: "w-confirmation",
    slug: "order-confirmation",
    title: "Order-Confirmation (Page + Mail)",
    category: "customer",
    stage: "stage-3",
    status: "planned",
    summary: "Erfolgsseite + automatische Bestellbestätigungs-Mail.",
    trigger: "Stripe-Webhook → markProcessed + sendOrderConfirmation",
    steps: [
      "Page liest Stripe-Session-ID aus URL",
      "Lädt Order via session_id (NICHT Order-ID)",
      "Zeigt: Bestellnummer HAG-2026-000042, Total, Items, Schätz-Lieferzeit",
      "Email-Trigger: HTML-Mail mit Bestellinhalt",
      "Tracking-URL für später (publicToken)",
    ],
    risks: [
      {
        id: "r-mail-spam",
        title: "Bestellbestätigung im Spam-Ordner",
        description: "SPF/DKIM/DMARC nicht sauber → Mail landet in Junk.",
        level: "high",
        consequence: "Kunde denkt Bestellung kaputt. Anruf-Volumen steigt.",
        mitigation: "DNS-Records sauber setzen. mail-tester.com vor Live. Plus: Confirmation-Page zeigt auch alle Infos.",
        mitigationStatus: "planned",
      },
      {
        id: "r-pii-leak-url",
        title: "Order-Details über URL leakable",
        description: "Wenn /bestellung-bestaetigt nur Order-ID nutzt, kann jeder /bestellung/123 raten.",
        level: "high",
        consequence: "PII-Leak. DSGVO-Verstoß.",
        mitigation: "publicToken (32 bytes base64url) statt Order-ID in URL.",
        mitigationStatus: "done",
        codeRef: "lib/security/tokens.ts",
      },
    ],
    security: [
      { id: "s-token-url", title: "Token-basierte URLs", description: "Crypto-Random 256-bit für Gast-Zugriff.", status: "done" },
      { id: "s-noindex-orders", title: "/bestellung-* noindex", description: "Robots-Meta.", status: "planned" },
    ],
    frontend: [
      { page: "Confirmation-Page", change: "Editorial mit Order-Summary + nächste Schritte", status: "planned" },
    ],
  },
  {
    id: "w-tracking",
    slug: "tracking-status",
    title: "Tracking-Status-Page",
    category: "customer",
    stage: "stage-3",
    status: "planned",
    summary: "Kunde verfolgt Order-Status über Token-URL aus Mail.",
    trigger: "Link aus Bestätigungs-Mail oder Versand-Mail",
    steps: [
      "URL /bestellung/status/[token]",
      "Token-Lookup → Order",
      "Zeigt Status (PENDING → PAID → SHIPPED → DELIVERED)",
      "Bei SHIPPED: Tracking-Link zu DHL/Spedition",
      "Bei DELIVERED: 'Wie war's?' → Bewertungsformular",
    ],
    risks: [
      {
        id: "r-idor",
        title: "IDOR über Order-ID-Brute-Force",
        description: "Angreifer rät publicToken — 256-bit-Token ist aber nicht ratebar.",
        level: "low",
        consequence: "Theoretisch PII-Leak, praktisch nicht möglich.",
        mitigation: "32-byte cryptographic random Token + DB-Index.",
        mitigationStatus: "done",
        codeRef: "lib/security/tokens.ts",
      },
      {
        id: "r-stale-token",
        title: "Token läuft nicht ab",
        description: "Jahre alte Tokens funktionieren noch.",
        level: "low",
        consequence: "Nach Account-Verlust durch User: Ex könnte Token nutzen.",
        mitigation: "Token-Ablauf nach 2 Jahren (Aufbewahrungsfrist).",
        mitigationStatus: "planned",
      },
    ],
    security: [
      { id: "s-token-rate-limit", title: "Token-Lookup Rate-Limit", description: "10/min pro IP gegen Brute-Force.", status: "planned" },
    ],
    frontend: [
      { page: "Tracking-Page", change: "Status-Timeline + Tracking-Link", status: "planned" },
    ],
  },
  {
    id: "w-pdf-rechnung",
    slug: "pdf-rechnung",
    title: "PDF-Rechnung + Lieferschein",
    category: "system",
    stage: "stage-3",
    status: "planned",
    summary: "React-PDF generiert § 14 UStG-konforme Rechnung + DHL-Lieferschein.",
    trigger: "Order-Status → PAID",
    steps: [
      "React-PDF rendert Rechnung mit Hagi-Stammdaten",
      "Pflicht-Angaben § 14 UStG: USt-ID, fortlaufende Rechnungsnummer, Datum, Leistung",
      "Kleinunternehmer-Hinweis falls TAX_MODE=small_business",
      "B2B-Variante: Reverse-Charge-Vermerk",
      "PDF in S3/Storage → Link in Mail",
      "Lieferschein separat für Versanddienstleister",
    ],
    risks: [
      {
        id: "r-rechnung-pflicht",
        title: "Rechnungsfehler § 14 UStG",
        description: "Pflichtangaben fehlen → Finanzamt verweigert Vorsteuer-Abzug bei B2B-Käufern.",
        level: "high",
        consequence: "Reklamationen von B2B-Käufern. Korrekturen.",
        mitigation: "Template gegen § 14 UStG-Checkliste validieren. Plus Steuerberater-Review.",
        mitigationStatus: "planned",
      },
      {
        id: "r-rechnung-leak",
        title: "PDF-URL ratbar / public",
        description: "Wenn /rechnung/123.pdf einfach erratbar — PII-Leak.",
        level: "high",
        consequence: "DSGVO + Wettbewerbs-Daten leaken.",
        mitigation: "PDFs hinter publicToken + Auth-Check.",
        mitigationStatus: "planned",
      },
    ],
    security: [
      { id: "s-pdf-token", title: "PDF nur per Token zugänglich", description: "URL = /rechnung/[publicToken].pdf.", status: "planned" },
      { id: "s-pdf-gobd", title: "GoBD-konforme Archivierung", description: "10 Jahre unveränderlich speichern.", status: "planned" },
    ],
    frontend: [
      { page: "Bestellbestätigung", change: "PDF-Download-Link", status: "planned" },
    ],
  },
  {
    id: "w-widerruf",
    slug: "widerruf-portal",
    title: "Widerruf / Rückgabe",
    category: "customer",
    stage: "stage-4",
    status: "planned",
    summary: "Self-Service-Portal für Widerrufserklärung mit Anlage-2-Formular.",
    trigger: "Kunde klickt Link aus Mail oder navigiert zu /widerruf/[token]",
    steps: [
      "Token-Lookup",
      "Zeigt Order-Details + Rückgabe-Formular",
      "Anlage 2 als PDF zum Ausdrucken",
      "Online-Widerruf direkt absendbar",
      "Bei Sonderanfertigung: 'Widerruf ausgeschlossen' (vorher Checkbox)",
      "Foto-Upload für Schadensdokumentation",
      "Trigger: Refund-Workflow im Admin",
    ],
    risks: [
      {
        id: "r-spedition-retoure",
        title: "Sperrgut-Rücksendung Kosten",
        description: "Großteppich zurück = 89 €. Wer zahlt?",
        level: "medium",
        consequence: "Streit über Kosten. Negative Reviews.",
        mitigation: "AGB klar regeln: Händler trägt bis 200 € Warenwert, darüber Kunde. Oder pauschal Händler.",
        mitigationStatus: "planned",
      },
      {
        id: "r-frist",
        title: "14-Tage-Frist falsch berechnet",
        description: "Kunde widerruft am Tag 15 → wir lehnen ab → war aber innerhalb der Frist (DHL-Verzögerung).",
        level: "medium",
        consequence: "Rechtsstreit verloren.",
        mitigation: "Frist beginnt mit Lieferung (deliveredAt) NICHT mit Bestellung.",
        mitigationStatus: "planned",
      },
    ],
    security: [
      { id: "s-photo-validation", title: "Foto-Upload MIME-Validation", description: "Nur JPG/PNG, max 5 MB, EXIF stripped.", status: "planned" },
    ],
    frontend: [
      { page: "Widerruf-Portal", change: "Editorial-Form mit Foto-Upload", status: "planned" },
    ],
  },
  {
    id: "w-admin-orders",
    slug: "admin-orders",
    title: "Admin-Dashboard Orders",
    category: "admin",
    stage: "stage-4",
    status: "planned",
    summary: "Hagi sieht alle Bestellungen, Status-Updates, Tracking-Nummer eingeben.",
    trigger: "Admin-Login → /admin/orders",
    steps: [
      "Liste aller Orders (paginiert, gefiltert)",
      "Filter: Status, Datum, Zahlungsart, B2B",
      "Click → Order-Detail",
      "Status-Update Buttons (Confirmed → Shipped → Delivered)",
      "Tracking-Nummer eingeben → Auto-Trigger sendShippingNotification()",
      "Refund-Button für Storno",
    ],
    risks: [
      {
        id: "r-admin-auth",
        title: "Admin-Auth umgangen",
        description: "Wenn /admin nicht properly geschützt → jeder hat Zugriff auf alle Orders.",
        level: "high",
        consequence: "Massiver PII-Leak. DSGVO-GAU.",
        mitigation: "argon2id Passwort + Session-Cookie + IP-Allowlist optional.",
        mitigationStatus: "planned",
      },
      {
        id: "r-mass-actions",
        title: "Mass-Refund per Klick",
        description: "Hagi klickt versehentlich 'Alle stornieren'.",
        level: "medium",
        consequence: "Unwiderrufliche Stornierungen.",
        mitigation: "Bulk-Actions hinter 2-Faktor-Bestätigung.",
        mitigationStatus: "planned",
      },
    ],
    security: [
      { id: "s-admin-csrf", title: "CSRF auf Admin-Routes", description: "Next.js Server Actions built-in.", status: "done" },
      { id: "s-audit-log", title: "Alle Admin-Aktionen auditiert", description: "logAudit() bei jedem Status-Change.", status: "done", codeRef: "lib/services/audit.ts" },
      { id: "s-2fa", title: "2FA für Hagi-Admin", description: "TOTP oder Magic-Link.", status: "planned" },
    ],
    frontend: [
      { page: "Admin-Dashboard", pageHref: "/admin", change: "Komplett neu, Editorial-Utilitarian", status: "planned" },
    ],
  },
  {
    id: "w-manual-order",
    slug: "manual-order",
    title: "Manuelle Order (Showroom-Walk-in)",
    category: "admin",
    stage: "stage-4",
    status: "planned",
    summary: "Hagi verkauft im Showroom → Order im Admin manuell anlegen → Inventar sync.",
    trigger: "Showroom-Verkauf",
    steps: [
      "Hagi: 'Neue Order' im Admin",
      "Produkt auswählen (Unikat: inStock=true noch?)",
      "Customer eintragen (Name, Adresse, Email optional)",
      "Zahlungsart: Bar, EC-Karte, Überweisung",
      "Order anlegen mit paymentStatus=PAID manuell",
      "Auto: Inventar inStock=false bei Unikat",
      "Optional: Rechnung an Kundenmail",
    ],
    risks: [
      {
        id: "r-inventory-sync",
        title: "Hagi vergisst Showroom-Verkauf einzutragen",
        description: "Online wird das Stück als verfügbar gezeigt.",
        level: "high",
        consequence: "Online-Doppelverkauf, manueller Storno, Vertrauensverlust.",
        mitigation: "Sofort-Eintrag-Verpflichtung. Plus täglicher Inventur-Check.",
        mitigationStatus: "planned",
      },
      {
        id: "r-cash-tax",
        title: "Bar-Verkauf steuerlich nicht erfasst",
        description: "Hagi vergisst manuelle Order anzulegen.",
        level: "medium",
        consequence: "Steuerstrafe.",
        mitigation: "POS-Pflicht oder manuelle Order zwingend.",
        mitigationStatus: "planned",
      },
    ],
    security: [
      { id: "s-manual-audit", title: "Manuelle Orders im AuditLog", description: "actorType='admin' separiert.", status: "done" },
    ],
    frontend: [
      { page: "/admin/orders/new", change: "Quick-Form für Showroom-Verkauf", status: "planned" },
    ],
  },
  {
    id: "w-emails",
    slug: "email-versand",
    title: "Email-Versand (Resend)",
    category: "system",
    stage: "stage-3",
    status: "in-progress",
    summary: "Transaktional: Bestellbestätigung, Tracking, Lieferung, Storno, Widerruf, Newsletter.",
    trigger: "Order-Lifecycle-Event oder Cron",
    steps: [
      "Order-Status-Change triggert Mail",
      "React-Email Template rendert HTML",
      "Resend API sendet via verifizierter Domain",
      "Webhook → unsere DB: Mail-Status (sent/bounced/spam)",
      "Bei Bounce: AuditLog + Retry-Logic",
    ],
    risks: [
      {
        id: "r-deliverability",
        title: "Mails landen im Spam",
        description: "Domain-Reputation niedrig in ersten Wochen.",
        level: "high",
        consequence: "Kunde glaubt nicht bestellt zu haben.",
        mitigation: "SPF + DKIM + DMARC sauber. Warmup-Phase. Plus: Confirmation-Page als Backup.",
        mitigationStatus: "planned",
      },
      {
        id: "r-email-injection",
        title: "Header-Injection über Customer-Name",
        description: "Customer-Name mit CR/LF könnte Mail-Header manipulieren.",
        level: "medium",
        consequence: "Spam-Versand über unsere Domain → Domain-Blacklist.",
        mitigation: "Resend sanitized automatisch. Plus: Name-Validation in Schema.",
        mitigationStatus: "done",
      },
      {
        id: "r-no-resend-key",
        title: "RESEND_API_KEY fehlt in Prod",
        description: "App startet, Order kommt, Mail-Send wirft.",
        level: "medium",
        consequence: "Order liegt ohne Mail, Customer ratlos.",
        mitigation: "Fail-Fast bei Boot in Production wenn KEY fehlt. Plus: Order trotzdem anlegen, Mail-Retry in Queue.",
        mitigationStatus: "planned",
      },
    ],
    security: [
      { id: "s-resend-template", title: "Templates escaped HTML", description: "React-Email escaped automatisch.", status: "done" },
    ],
    frontend: [
      { page: "Email-Preview-Page (intern)", change: "/admin/emails/preview für Testing", status: "planned" },
    ],
  },
  {
    id: "w-spedition",
    slug: "spedition-grossteppich",
    title: "Spedition für Großteppiche",
    category: "admin",
    stage: "operations",
    status: "planned",
    summary: "Manueller Workflow: Spedition organisieren bei Sperrgut-Versand.",
    trigger: "Order mit shippingRate='Spedition'",
    steps: [
      "Order eingehend mit shippingRate='spedition'",
      "Order-Status: awaiting_spedition_confirmation (custom)",
      "Auto-Mail an Hagi: 'Spedition organisieren'",
      "Hagi ruft Kunde an, vereinbart Termin",
      "Hagi bucht Spedition (extern, nicht in App)",
      "Hagi trägt Spedition-Tracking-Nummer ein",
      "Status: SHIPPED",
    ],
    risks: [
      {
        id: "r-spedition-cost-overrun",
        title: "Spedition teurer als pauschale 89 €",
        description: "Berlin = 150 €.",
        level: "medium",
        consequence: "Hagi zahlt drauf.",
        mitigation: "Spedition-Pauschale gestaffelt nach PLZ-Bereich. Oder transparent abrechnen.",
        mitigationStatus: "planned",
      },
      {
        id: "r-spedition-damage",
        title: "Schaden während Spedition",
        description: "Häufiger als bei DHL.",
        level: "high",
        consequence: "Komplexer Schadensprozess, Versicherungsstreit.",
        mitigation: "Versicherung beim Spediteur. Pflicht-Foto-Dokumentation bei Lieferung.",
        mitigationStatus: "planned",
      },
    ],
    security: [
      { id: "s-customer-phone-required", title: "Telefon Pflicht für Spedition", description: "Sonst kann Spedition nicht ausliefern.", status: "planned" },
    ],
    frontend: [
      { page: "Checkout", change: "Bei Spedition: Telefon Pflichtfeld", status: "planned" },
    ],
  },
  {
    id: "w-dsgvo",
    slug: "dsgvo-loeschung",
    title: "DSGVO Auskunft + Löschung",
    category: "compliance",
    stage: "stage-5",
    status: "planned",
    summary: "Customer-Recht auf Auskunft + Löschung. Orders bleiben (Buchhaltungs-Pflicht 10 Jahre).",
    trigger: "Customer-Email an datenschutz@hagi-teppiche.de",
    steps: [
      "Hagi erhält Anfrage per Mail",
      "Admin-Dashboard: 'Customer suchen'",
      "Auskunft: Export aller Daten als JSON+PDF",
      "Löschung: Customer.deletedAt + anonymizedAt + Customer-Felder NULL",
      "Order-Snapshots bleiben (10 Jahre AO §147)",
      "ConsentLog bleibt als Beweis",
      "Innerhalb 30 Tagen erledigen (DSGVO Art. 12)",
    ],
    risks: [
      {
        id: "r-dsgvo-fristen",
        title: "30-Tage-Frist verpasst",
        description: "Hagi vergisst Anfragen.",
        level: "high",
        consequence: "Bußgeld bis 20 Mio. €.",
        mitigation: "Auto-Reminder im Admin. Ticket-System für DSGVO-Anfragen.",
        mitigationStatus: "planned",
      },
      {
        id: "r-pii-residue",
        title: "PII bleibt in Backups",
        description: "Postgres-Backup von vor Löschung enthält noch alles.",
        level: "medium",
        consequence: "Wenn Backup restored: PII zurück.",
        mitigation: "Backup-Retention max 30 Tage. Restore-Process inkl. Re-Anonymization.",
        mitigationStatus: "planned",
      },
    ],
    security: [
      { id: "s-soft-delete", title: "Soft-Delete für Customer", description: "deletedAt + anonymizedAt im Schema.", status: "done", codeRef: "prisma/schema.prisma" },
      { id: "s-pii-snapshot", title: "PII auf Order snapshotted", description: "Buchhaltung bleibt, Customer kann weg.", status: "done" },
      { id: "s-consent-versioned", title: "ConsentLog versioniert", description: "AGB-Version snapshotted.", status: "done", codeRef: "lib/services/consent.ts" },
    ],
    frontend: [
      { page: "/admin/customers/search", change: "Suche + Auskunft + Löschung", status: "planned" },
      { page: "Datenschutz-Page", change: "Rechte des Betroffenen klar", status: "in-progress" },
    ],
  },
  {
    id: "w-cron",
    slug: "background-jobs",
    title: "Background-Jobs (Cron)",
    category: "system",
    stage: "stage-5",
    status: "planned",
    summary: "Tägliche/stündliche Aufgaben: Abandoned-Cart, PII-Retention, Stripe-Reconciliation.",
    trigger: "Cron via Vercel/Coolify",
    steps: [
      "Hourly: Stripe-Sessions vs DB reconcile (fehlende Webhooks fangen)",
      "Daily: Abandoned-Cart-Reminder 4h/24h/72h",
      "Daily: PII-Retention (PII auf Orders > 10 Jahre alt anonymisieren)",
      "Weekly: AuditLog-Old-Records archivieren",
      "Daily: Inventur-Check (Unikate Out-of-Stock)",
    ],
    risks: [
      {
        id: "r-cron-failure",
        title: "Cron-Failure unentdeckt",
        description: "Cron läuft nicht, niemand merkt es.",
        level: "medium",
        consequence: "Abandoned-Cart-Mails fehlen, Reconciliation kaputt.",
        mitigation: "Heartbeat-Logging + Alert bei Ausfall.",
        mitigationStatus: "planned",
      },
      {
        id: "r-cron-double-run",
        title: "Cron läuft 2x → Doppel-Mails",
        description: "Vercel-Cron + lokaler Cron beide aktiv.",
        level: "medium",
        consequence: "Spam für Kunden.",
        mitigation: "Idempotency: jede Cart-Recovery-Mail mit lastReminderAt-Marker.",
        mitigationStatus: "planned",
      },
    ],
    security: [
      { id: "s-cron-auth", title: "Cron-Endpoints mit Secret-Header", description: "CRON_SECRET in ENV.", status: "planned" },
    ],
    frontend: [
      { page: "/admin/jobs", change: "Cron-Status-Dashboard", status: "planned" },
    ],
  },
];
